var skills = [
    "Ancestral Protector",
    "Ancestral Warchief",
    "Animate Weapon",
    "Ball Lightning",
    "Barrage",
    "Blade Flurry",
    "Blade Vortex",
    "Bladefall",
    "Blast Rain",
    "Blight",
    "Bodyswap",
    "Burning Arrow",
    "Caustic Arrow",
    "Charged Dash",
    "Cleave",
    "Cremation",
    "Cold Snap",
    "Cyclone",
    "Dark Pact",
    "Detonate Dead",
    "Discharge",
    "Dominating Blow",
    "Double Strike",
    "Dual Strike",
    "Earthquake",
    "Elemental Hit",
    "Essence Drain",
    "Ethereal Knives",
    "Explosive Arrow",
    "Explosive Trap",
    "Fire Nova Mine",
    "Fire Trap",
    "Fireball",
    "Firestorm",
    "Flame Surge",
    "Flame Totem",
    "Flameblast",
    "Freeze Mine",
    "Freezing Pulse",
    "Frenzy",
    "Frost Blades",
    "Frostbolt",
    "Glacial Cascade",
    "Glacial Hammer",
    "Ground Slam",
    "Heavy Strike",
    "Ice Crash",
    "Ice Nova",
    "Ice Shot",
    "Ice Spear",
    "Ice Trap",
    "Incinerate",
    "Infernal Blow",
    "Kinetic Blast",
    "Lacerate",
    "Leap Slam",
    "Lightning Arrow",
    "Lightning Strike",
    "Lightning Tendrils",
    "Lightning Trap",
    "Lightning Warp",
    "Magma Orb",
    "Molten Strike",
    "Power Siphon",
    "Puncture",
    "Rain of Arrows",
    "Raise Spectre",
    "Raise Zombie",
    "Righteous Fire",
    "Reave",
    "Searing Bond",
    "Scorching Ray",
    "Shield Charge",
    "Shock Nova",
    "Shockwave Totem",
    "Shrapnel Shot",
    "Siege Ballista",
    "Spark",
    "Spectral Shield Throw",
    "Split Arrow",
    "Static Strike",
    "Storm Burst",
    "Storm Call",
    "Summon Raging Spirit",
    "Summon Skeleton",
    "Sunder",
    "Sweep",
    "Tectonic Slam",
    "Tornado Shot",
    "Unearth",
    "Viper Strike",
    "Volatile Dead",
    "Vortex",
    "Wild Strike",
    "Wither"
];
